name: Build Base Image
run-name: Build base image.
on: workflow_dispatch
jobs:
  Build-Base-Image:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was triggered by a ${{ github.event_name }} event."